apiVersion: lvm.topolvm.io/v1alpha1
kind: LVMCluster
metadata:
  name: lvm-cluster
  namespace: openshift-storage
spec:
  storage:
    deviceClasses:
      - default: true
        fstype: xfs
        name: vg1
        nodeSelector:
          nodeSelectorTerms:
            - matchExpressions:
                # - key: node-role.kubernetes.io/worker
                #   operator: Exists
                - key: node-role.kubernetes.io/lvm
                  operator: Exists
        thinPoolConfig:
          name: thin-pool-1
          overprovisionRatio: 10
          sizePercent: 90
