apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - pvc.yaml

patches:
  - target:
      kind: Config
      name: cluster
    patch: |-
      - op: replace
        path: /spec
        value:
          managementState: Managed
          rolloutStrategy: Recreate
          replicas: 1
          storage:
            managementState: Unmanaged
            pvc:
              claim: registry-storage-pvc
